use soroban_sdk::contracterror;

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum Error {
    SessionNotFound = 1,
    InvalidExpiry = 2,
    InvalidPolicy = 3,
    NonCanonicalField = 4,
    AssetNotAllowed = 5,
    InvalidLifecycle = 6,
    WrongSettlementMode = 7,
    SessionFrozen = 8,
    SessionExpired = 9,
    InvalidAmount = 10,
    IdentifierAlreadyUsed = 11,
    CounterOverflow = 12,
    BudgetNoteNotFound = 13,
    BudgetNodeNotFound = 14,
    InvalidBudgetOwner = 15,
    BudgetNoteSpent = 16,
    InvalidNodeState = 17,
    BranchFrozen = 18,
    InvalidChildPolicy = 19,
    InvalidConservation = 20,
    InvalidAgentAccount = 21,
    BudgetStateMismatch = 22,
    InvalidAddressEncoding = 23,
    InvalidProof = 24,
    AuditStateNotFound = 25,
    PaymentAlreadySettled = 26,
    ProviderNotApproved = 27,
    CategoryNotAllowed = 28,
    ActionNotAllowed = 29,
    AuditStateMismatch = 30,
    ReservationNotFound = 31,
    ReservationAlreadyExists = 32,
    VoucherKeyAlreadyUsed = 33,
    InvalidReservation = 34,
    InvalidVoucher = 35,
    InvalidPrivateSettlement = 36,
    UnresolvedReservations = 37,
    AuditAlreadyFinalized = 38,
    AuditNotFinalized = 39,
    FinalAuditSnapshotNotFound = 40,
}
